### PR TITLE
fix: better stop at eof

### LINKED ISSUE #72: Stop at end of file
image

image

I want the scolling to stop at the last line like in the first picture not sure if this is already configurable

### PR DESCRIPTION
**Pull request by LostNeophyte**
fixes #72 
before:

https://user-images.githubusercontent.com/110467150/206856163-0097b4a1-d291-4114-a7d4-73b76b6ceabb.mp4

after:

https://user-images.githubusercontent.com/110467150/206856220-1b354fd5-9260-4100-9ec6-3be18ee0a7ea.mp4

### CODE REVIEW

**Comment by amalgame21** [comment]
<C-f> and <C-d> is not working when content is less than one window height and the first line is hovered.

**Comment by LostNeophyte** [comment]
> `Ctrl-f` and `Ctrl-d` is not working when content is less than one window height and the first line is hovered.

Thanks for reporting that, should be fixed now

**Comment by karb94** [comment]
@LostNeophyte thank you for fixing this issue. Great work!

**Comment by marcelja** [comment]
@karb94 Do you think you could take a look?

**Comment by karb94** [comment]
For some reason I can't seem to reproduce the issue. For me the two videos shared by @LostNeophyte are the difference between setting `stop_eof` as `true` (default; second video) or `false` (first video). I also have some tests to cover this behaviour. Does this always happen with default configuration? What version of neovim are you using?

I haven't had time to look into the specific changes but as it is this PR is failing 7 of the tests I have in `lua/tests` so it can't be merged yet. You can run the tests using plenary `test_harness` module.

**Comment by marcelja** [comment]
I'm on nvim v0.9.1 and have the default configuration. When I have a small file and scroll down, the lines below cursor are not equal to the win lines below cursor. In this screenshot for example, `data.lines_below_cursor` is 3 and `data.win_lines_below_cursor` is 12. Therefore, the function is not returning true and I don't see the first lines of the file after scrolling.

image

**Comment by joalof** [comment]
I'm also on Neovim 0.9.1 and `stop_eof` has no effect for me either.

**Comment by karb94** [comment]
@marcelja I think understand your specific issue. You expect that when the file has less lines than the window it should not scroll the window further and it should behave as if it has reached EOF. Then the cursor will scroll down on its own or not depending on the `cursor_scrolls_alone` setting. This is a bug and I will work on a fix.

However, I don't think this is the issue that @LostNeophyte has shown in the videos where you can see that the file spans more than a window. I cannot reproduce OP's scenario but maybe I'm missing something. Below is the behaviour I get with the default settings.

## `stop_eof = true`

https://github.com/karb94/neoscroll.nvim/assets/41967813/6e8dcac5-54f2-4454-b472-7210b4f63c88

## `stop_eof = false`

https://github.com/karb94/neoscroll.nvim/assets/41967813/5c34bfa5-2566-425e-9d49-c846f1fd666d

**Comment by LostNeophyte** [comment]
@karb94 I was on vacation, I'm back now
during the testing now I discovered that the problem is 100% reproducible with winbar, without it I have no reliable way of reproducing (I had a config that reproduced it, I removed a comment form that config and now it can't reproduce the bug, I added the same exact comment is the same place and I couldn't reproduce it)

can you reproduce the bug like this?
1.  `nvim +help +"set winbar=hi" +"normal G3k"`
2. `<C-d>` (this shouldn't move the window, just the cursor)

**Comment by karb94** [comment]
Thanks @LostNeophyte, this is very helpful. I can reproduce it now. I'll take a look over the weekend.

**Comment by karb94** [comment]
Can you please try #74 ([stop_eof_fix branch](/karb94/neoscroll.nvim/tree/stop_eof_fix)). I've decided to stop scrolling the window if the last line of the file is visible. I think this is the closest behaviour to how (neo)vim scrolling works by default.

**Comment by LostNeophyte** [comment]
@karb94 LGTM, tested in 3 configs.
thanks!

**Pull request closed without merging**
