### PR TITLE
Add time_scale option

### PR DESCRIPTION
**Pull request by tobdub**
Add an option to adjust the time of scroll animations. Can be used to easily speed up or slow down all scroll animations.

### CODE REVIEW

**Comment by s1n7ax** [comment]
I have been using this for two days with 500 ms time. I haven't had any issues so far. This is must have feature IMO.

**Comment by antonkesy** [comment]
friendly ping

**Review by karb94 — CHANGES_REQUESTED** [review]
Thank you for this. Could you add this new setting to the [Options](https://github.com/karb94/neoscroll.nvim#options) section in the README? Then I'll be happy to merge this.

**Comment by karb94** [comment]
Closing as the feature has just been added in 81c47f9d111c00d13111b65bfd13cc81b7b347a1

**Pull request closed without merging**
